package com.midnight.engage.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APPS".
 */
public class Apps {

    private Long id;
    private String Pack;
    private String Installed;
    private String Single;
    private String Cost;

    public Apps() {
    }

    public Apps(Long id) {
        this.id = id;
    }

    public Apps(Long id, String Pack, String Installed, String Single, String Cost) {
        this.id = id;
        this.Pack = Pack;
        this.Installed = Installed;
        this.Single = Single;
        this.Cost = Cost;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPack() {
        return Pack;
    }

    public void setPack(String Pack) {
        this.Pack = Pack;
    }

    public String getInstalled() {
        return Installed;
    }

    public void setInstalled(String Installed) {
        this.Installed = Installed;
    }

    public String getSingle() {
        return Single;
    }

    public void setSingle(String Single) {
        this.Single = Single;
    }

    public String getCost() {
        return Cost;
    }

    public void setCost(String Cost) {
        this.Cost = Cost;
    }

}
