package com.midnight.engage.Dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usersDaoConfig;
    private final DaoConfig appsDaoConfig;

    private final UsersDao usersDao;
    private final AppsDao appsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        appsDaoConfig = daoConfigMap.get(AppsDao.class).clone();
        appsDaoConfig.initIdentityScope(type);

        usersDao = new UsersDao(usersDaoConfig, this);
        appsDao = new AppsDao(appsDaoConfig, this);

        registerDao(Users.class, usersDao);
        registerDao(Apps.class, appsDao);
    }
    
    public void clear() {
        usersDaoConfig.getIdentityScope().clear();
        appsDaoConfig.getIdentityScope().clear();
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

    public AppsDao getAppsDao() {
        return appsDao;
    }

}
