package com.midnight.engage.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USERS".
 */
public class Users {

    private Long id;
    private String imageUrl;
    private String username;
    private String password;
    private String coins;

    public Users() {
    }

    public Users(Long id) {
        this.id = id;
    }

    public Users(Long id, String imageUrl, String username, String password, String coins) {
        this.id = id;
        this.imageUrl = imageUrl;
        this.username = username;
        this.password = password;
        this.coins = coins;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getCoins() {
        return coins;
    }

    public void setCoins(String coins) {
        this.coins = coins;
    }

}
