/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_soft_adi_engage_Global.h>
#include <jni.h>
/* Header for class com_soft_adi_famous_instagram_Global */


/*
 * Class:     com_soft_adi_famous_instagram_Global
 * Method:    HelloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_midnight_engage_Global_HelloJNI
 (JNIEnv *env , jobject obj) {
   (*env)->NewStringUTF(env , "DA8B9B217DE9E228https://i.instagram.com/api/v1/");
}




